version: '2'
services:
    selenium-hub:
        restart: always
        image: selenium/hub:3.141.0
        container_name: 'selenium-hub'
        ports:
            - '4444:4444'
    chrome:
        restart: always
        image: selenium/node-chrome-debug:3.141.0
        container_name: 'chrome'
        environment:
            HUB_HOST: selenium-hub
        ports:
            - '5900:5900'
        volumes:
            - /dev/shm:/dev/shm
        depends_on:
            - selenium-hub
    python:
      build: .
      container_name: 'python'
      links:
        - selenium-hub:hub
      command: 'tail -f /dev/null'
      volumes:
        - .:/opt/app

